import { IProduct } from "@/types/product";
import { ICategory } from "@/types/category";

export const FALLBACK_CATEGORIES: ICategory[] = [
  { _id: "cat-1", name: "Diamond Jewelry", slug: "diamond-jewelry", order: 1, isActive: true, createdAt: "", updatedAt: "" },
  { _id: "cat-2", name: "Gold & Luxury Jewelry", slug: "gold-luxury-jewelry", order: 2, isActive: true, createdAt: "", updatedAt: "" },
  { _id: "cat-3", name: "Children's Wears", slug: "childrens-wears", order: 3, isActive: true, createdAt: "", updatedAt: "" },
  { _id: "cat-4", name: "Fashion Accessories", slug: "fashion-accessories", order: 4, isActive: true, createdAt: "", updatedAt: "" },
  { _id: "cat-5", name: "Premium Gifts", slug: "premium-gifts", order: 5, isActive: true, createdAt: "", updatedAt: "" },
];

export const FALLBACK_PRODUCTS: IProduct[] = [
  // Diamond Jewelry
  {
    _id: "p1", name: "Diamond Necklace", slug: "diamond-necklace",
    description: "Exquisite diamond necklace featuring brilliant-cut stones set in 18K white gold.",
    price: 2500000, images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=800&fit=crop"],
    category: { _id: "cat-1", name: "Diamond Jewelry", slug: "diamond-jewelry" },
    inventory: 5, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p2", name: "Diamond Ring", slug: "diamond-ring",
    description: "Stunning solitaire diamond ring in a platinum setting with 1.5-carat diamond.",
    price: 1800000, images: ["https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&h=800&fit=crop"],
    category: { _id: "cat-1", name: "Diamond Jewelry", slug: "diamond-jewelry" },
    inventory: 8, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p3", name: "Diamond Stud Earrings", slug: "diamond-stud-earrings",
    description: "Classic diamond stud earrings with 0.75-carat total weight in 14K white gold.",
    price: 1200000, images: ["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&h=800&fit=crop"],
    category: { _id: "cat-1", name: "Diamond Jewelry", slug: "diamond-jewelry" },
    inventory: 10, isJustArrived: false, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p4", name: "Diamond Tennis Bracelet", slug: "diamond-tennis-bracelet",
    description: "Stunning 5-carat diamond tennis bracelet in 18K white gold with 42 diamonds.",
    price: 3200000, images: ["https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800&h=800&fit=crop"],
    category: { _id: "cat-1", name: "Diamond Jewelry", slug: "diamond-jewelry" },
    inventory: 3, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p5", name: "Diamond Pendant", slug: "diamond-pendant",
    description: "Elegant pear-shaped diamond pendant on an 18K white gold chain.",
    price: 1450000, images: ["https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=800&h=800&fit=crop"],
    category: { _id: "cat-1", name: "Diamond Jewelry", slug: "diamond-jewelry" },
    inventory: 6, isJustArrived: false, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p6", name: "Diamond Eternity Band", slug: "diamond-eternity-band",
    description: "Full eternity band featuring 2.5 carats of round brilliant diamonds in platinum.",
    price: 2100000, images: ["https://images.unsplash.com/photo-1603561596112-0a132b757442?w=800&h=800&fit=crop"],
    category: { _id: "cat-1", name: "Diamond Jewelry", slug: "diamond-jewelry" },
    inventory: 4, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  // Gold & Luxury Jewelry
  {
    _id: "p7", name: "Gold Bracelet", slug: "gold-bracelet",
    description: "Luxurious 18K gold bracelet with intricate filigree design.",
    price: 950000, images: ["https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop"],
    category: { _id: "cat-2", name: "Gold & Luxury Jewelry", slug: "gold-luxury-jewelry" },
    inventory: 12, isJustArrived: false, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p8", name: "Gold Chain Necklace", slug: "gold-chain-necklace",
    description: "Bold 22K gold Cuban link chain necklace, 20 inches of pure luxury.",
    price: 1650000, images: ["https://images.unsplash.com/photo-1515562141589-67f0d569b6fc?w=800&h=800&fit=crop"],
    category: { _id: "cat-2", name: "Gold & Luxury Jewelry", slug: "gold-luxury-jewelry" },
    inventory: 7, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p9", name: "Gold Hoop Earrings", slug: "gold-hoop-earrings",
    description: "Sleek 18K gold hoop earrings with polished finish, lightweight and comfortable.",
    price: 420000, images: ["https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&h=800&fit=crop"],
    category: { _id: "cat-2", name: "Gold & Luxury Jewelry", slug: "gold-luxury-jewelry" },
    inventory: 15, isJustArrived: false, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p10", name: "Pearl & Gold Necklace", slug: "pearl-gold-necklace",
    description: "Exquisite freshwater pearl necklace with 14K gold accents and clasp.",
    price: 780000, images: ["https://images.unsplash.com/photo-1515562141589-67f0d569b6fc?w=800&h=800&fit=crop"],
    category: { _id: "cat-2", name: "Gold & Luxury Jewelry", slug: "gold-luxury-jewelry" },
    inventory: 6, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p11", name: "Gold Cuff Bracelet", slug: "gold-cuff-bracelet",
    description: "Modern 18K gold cuff bracelet with hammered texture finish.",
    price: 720000, images: ["https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop"],
    category: { _id: "cat-2", name: "Gold & Luxury Jewelry", slug: "gold-luxury-jewelry" },
    inventory: 8, isJustArrived: false, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p12", name: "Gold Signet Ring", slug: "gold-signet-ring",
    description: "Classic 18K gold signet ring with flat oval face for engraving.",
    price: 580000, images: ["https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800&h=800&fit=crop"],
    category: { _id: "cat-2", name: "Gold & Luxury Jewelry", slug: "gold-luxury-jewelry" },
    inventory: 9, isJustArrived: false, isActive: true, createdAt: "", updatedAt: "",
  },
  // Children's Wears
  {
    _id: "p13", name: "Children Designer Outfit", slug: "children-designer-outfit",
    description: "Premium designer outfit for children aged 3-8 years.",
    price: 75000, images: ["https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&h=800&fit=crop"],
    category: { _id: "cat-3", name: "Children's Wears", slug: "childrens-wears" },
    inventory: 20, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p14", name: "Luxury Kids Shoes", slug: "luxury-kids-shoes",
    description: "Handcrafted Italian leather shoes for kids.",
    price: 45000, images: ["https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&h=800&fit=crop"],
    category: { _id: "cat-3", name: "Children's Wears", slug: "childrens-wears" },
    inventory: 15, isJustArrived: false, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p15", name: "Kids Party Dress", slug: "kids-party-dress",
    description: "Beautiful tulle party dress for girls aged 4-10 with delicate embroidery.",
    price: 65000, images: ["https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800&h=800&fit=crop"],
    category: { _id: "cat-3", name: "Children's Wears", slug: "childrens-wears" },
    inventory: 18, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p16", name: "Boys Formal Suit Set", slug: "boys-formal-suit-set",
    description: "Three-piece suit set for boys aged 3-12 in premium wool blend.",
    price: 85000, images: ["https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800&h=800&fit=crop"],
    category: { _id: "cat-3", name: "Children's Wears", slug: "childrens-wears" },
    inventory: 12, isJustArrived: false, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p17", name: "Kids Sneakers Collection", slug: "kids-sneakers-collection",
    description: "Trendy designer sneakers for kids with cushioned soles.",
    price: 35000, images: ["https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=800&h=800&fit=crop"],
    category: { _id: "cat-3", name: "Children's Wears", slug: "childrens-wears" },
    inventory: 25, isJustArrived: false, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p18", name: "Baby Gift Set", slug: "baby-gift-set",
    description: "Premium baby gift set with romper, bib, booties, and blanket.",
    price: 55000, images: ["https://images.unsplash.com/photo-1522771930-78848d9293e8?w=800&h=800&fit=crop"],
    category: { _id: "cat-3", name: "Children's Wears", slug: "childrens-wears" },
    inventory: 20, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  // Fashion Accessories
  {
    _id: "p19", name: "Leather Designer Handbag", slug: "leather-designer-handbag",
    description: "Premium Italian leather handbag with gold-tone hardware.",
    price: 320000, images: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&h=800&fit=crop"],
    category: { _id: "cat-4", name: "Fashion Accessories", slug: "fashion-accessories" },
    inventory: 10, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p20", name: "Luxury Sunglasses", slug: "luxury-sunglasses",
    description: "Polarized luxury sunglasses with titanium frames and UV400 protection.",
    price: 185000, images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&h=800&fit=crop"],
    category: { _id: "cat-4", name: "Fashion Accessories", slug: "fashion-accessories" },
    inventory: 14, isJustArrived: false, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p21", name: "Designer Watch", slug: "designer-watch",
    description: "Elegant automatic timepiece with sapphire crystal and leather strap.",
    price: 450000, images: ["https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&h=800&fit=crop"],
    category: { _id: "cat-4", name: "Fashion Accessories", slug: "fashion-accessories" },
    inventory: 5, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p22", name: "Premium Leather Belt", slug: "premium-leather-belt",
    description: "Full-grain Italian leather belt with brushed gold buckle.",
    price: 68000, images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop"],
    category: { _id: "cat-4", name: "Fashion Accessories", slug: "fashion-accessories" },
    inventory: 18, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p23", name: "Silk Designer Scarf", slug: "silk-designer-scarf",
    description: "100% mulberry silk scarf with hand-rolled edges in jewel tones.",
    price: 95000, images: ["https://images.unsplash.com/photo-1601924921557-45e8e0e22074?w=800&h=800&fit=crop"],
    category: { _id: "cat-4", name: "Fashion Accessories", slug: "fashion-accessories" },
    inventory: 20, isJustArrived: false, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p24", name: "Clutch Evening Bag", slug: "clutch-evening-bag",
    description: "Glamorous crystal-embellished clutch with detachable chain strap.",
    price: 150000, images: ["https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=800&h=800&fit=crop"],
    category: { _id: "cat-4", name: "Fashion Accessories", slug: "fashion-accessories" },
    inventory: 8, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p25", name: "Cashmere Beanie", slug: "cashmere-beanie",
    description: "Ultra-soft 100% cashmere beanie in classic ribbed knit.",
    price: 42000, images: ["https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=800&h=800&fit=crop"],
    category: { _id: "cat-4", name: "Fashion Accessories", slug: "fashion-accessories" },
    inventory: 22, isJustArrived: false, isActive: true, createdAt: "", updatedAt: "",
  },
  // Premium Gifts
  {
    _id: "p26", name: "Crystal Perfume Set", slug: "crystal-perfume-set",
    description: "Luxury perfume gift set with three fragrances in crystal bottles.",
    price: 280000, images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&h=800&fit=crop"],
    category: { _id: "cat-5", name: "Premium Gifts", slug: "premium-gifts" },
    inventory: 10, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p27", name: "Luxury Pen Collection", slug: "luxury-pen-collection",
    description: "Fountain pen and ballpoint set in lacquered metal with gold accents.",
    price: 165000, images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&h=800&fit=crop"],
    category: { _id: "cat-5", name: "Premium Gifts", slug: "premium-gifts" },
    inventory: 15, isJustArrived: false, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p28", name: "Premium Chocolate Box", slug: "premium-chocolate-box",
    description: "36 handcrafted Belgian truffles in exotic flavours.",
    price: 85000, images: ["https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&h=800&fit=crop"],
    category: { _id: "cat-5", name: "Premium Gifts", slug: "premium-gifts" },
    inventory: 25, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p29", name: "Luxury Spa Gift Box", slug: "luxury-spa-gift-box",
    description: "Indulgent spa box with bath bombs, body oil, face mask and more.",
    price: 120000, images: ["https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&h=800&fit=crop"],
    category: { _id: "cat-5", name: "Premium Gifts", slug: "premium-gifts" },
    inventory: 14, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p30", name: "Engraved Money Clip", slug: "engraved-money-clip",
    description: "Stainless steel money clip with 18K gold plating, personalizable.",
    price: 38000, images: ["https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=800&h=800&fit=crop"],
    category: { _id: "cat-5", name: "Premium Gifts", slug: "premium-gifts" },
    inventory: 30, isJustArrived: true, isActive: true, createdAt: "", updatedAt: "",
  },
  {
    _id: "p31", name: "Wine & Glass Gift Set", slug: "wine-glass-gift-set",
    description: "Premium red wine with two hand-blown crystal glasses in a wooden crate.",
    price: 195000, images: ["https://images.unsplash.com/photo-1474722883778-792e7990302f?w=800&h=800&fit=crop"],
    category: { _id: "cat-5", name: "Premium Gifts", slug: "premium-gifts" },
    inventory: 7, isJustArrived: false, isActive: true, createdAt: "", updatedAt: "",
  },
];
